application: blockdiag-hrd
version: 1
runtime: python27
threadsafe: true
api_version: 1
libraries:
- name: PIL
  version: "latest"
handlers:
- url: /static
  static_dir: static

- url: /tasks/.*
  script: main.app
  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /(\?src=.*)?
  static_files: static/html/blockdiag.html
  upload: static/html/blockdiag.html

- url: /(.*)/(\?src=.*)?
  static_files: static/html/\1.html
  upload: static/html/(.*).html

- url: .*
  script: main.app
