application: blockdiag
version: 1
runtime: python
api_version: 1
handlers:
- url: /static
  static_dir: static

- url: /tasks/.*
  script: main.py
  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /(\?src=.*)?
  static_files: static/html/blockdiag.html
  upload: static/html/blockdiag.html

- url: /(.*)/(\?src=.*)?
  static_files: static/html/\1.html
  upload: static/html/(.*).html

- url: .*
  script: main.py
