application: blockdiag
version: 1
runtime: python
threadsafe: true
api_version: 1
handlers:
- url: /static
  static_dir: static

- url: /tasks/.*
  script: main.py
  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /(\?src=.*)?
  static_files: static/blockdiag/index.html
  upload: static/blockdiag/index.html

- url: /(.*)/(\?src=.*)?
  static_files: static/\1/index.html
  upload: static/(.*)/index.html

- url: .*
  script: main.py
